--/PARTE 1 DA LISTA/--------------------------------------------------------------------
--/A)/--------------------------------------------------------------------
DELETE FROM CUSTOMER
WHERE CDCUSTOMER NOT IN (SELECT CDCUSTOMER FROM REQUEST)
--/B)/--------------------------------------------------------------------
DELETE FROM SUPPLIER 
WHERE CDSUPPLIER NOT IN (SELECT CDSUPPLIER FROM PRODUCT)
--/C)/--------------------------------------------------------------------
UPDATE PRODUCTREQUEST
SET VLUNITARY = PRODUCT.VLPRICE
FROM PRODUCTREQUEST INNER JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT
--/D)/--------------------------------------------------------------------
ALTER TABLE SUPPLIER
ADD DSSTATUS VARCHAR(10)
--/E)/--------------------------------------------------------------------
UPDATE SUPPLIER
SET DSSTATUS = 'INATIVO'
FROM SUPPLIER JOIN PRODUCT ON SUPPLIER.CDSUPPLIER = PRODUCT.CDSUPPLIER
WHERE SUPPLIER.CDSUPPLIER NOT LIKE PRODUCT.CDSUPPLIER
--/F)/--------------------------------------------------------------------
UPDATE CUSTOMER
SET NMADRESS = 'DESCONHECIDO'
WHERE NMADRESS IS NULL
--/G)/--------------------------------------------------------------------
INSERT INTO PRODUCTREQUEST (CDREQUEST, CDPRODUCT, QTAMOUNT, VLUNITARY)
SELECT PRODUCTREQUEST.CDREQUEST, PRODUCT.CDPRODUCT, 10, PRODUCT.VLPRICE
FROM PRODUCTREQUEST 
JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT
JOIN REQUEST ON PRODUCTREQUEST.CDREQUEST = REQUEST.CDREQUEST
--/PARTE 2 DA LISTA/--------------------------------------------------------------------
--/A)/--------------------------------------------------------------------
SELECT 
CUSTOMER.NMCUSTOMER, PRODUCT.NMPRODUCT,
COUNT(PRODUCTREQUEST.CDPRODUCT) AS QTPURCHASE,
SUM(PRODUCTREQUEST.QTAMOUNT) AS TOTALPURCHASED,
SUM(PRODUCTREQUEST.VLUNITARY) AS TOTALPAID
FROM PRODUCTREQUEST
JOIN REQUEST ON REQUEST.CDREQUEST = PRODUCTREQUEST.CDREQUEST
JOIN CUSTOMER ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER
JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT
GROUP BY NMCUSTOMER, NMPRODUCT
--/B)/--------------------------------------------------------------------
SELECT 
CUSTOMER.NMCUSTOMER, REQUEST.DTREQUEST,
COUNT(REQUEST.CDREQUEST) AS NUMREQUEST,
SUM(REQUEST.VLTOTAL) AS TOTALPERCUSTOMER
FROM REQUEST
JOIN CUSTOMER ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER
GROUP BY NMCUSTOMER, DTREQUEST
HAVING YEAR(DTREQUEST) = 2003 
--/C)/--------------------------------------------------------------------
SELECT
SUPPLIER.NMSUPPLIER,
SUPPLIER.IDFONE,
PRODUCT.NMPRODUCT,
PRODUCT.VLPRICE,
PRODUCT.QTSTOCK
FROM PRODUCT 
LEFT JOIN SUPPLIER ON SUPPLIER.CDSUPPLIER = PRODUCT.CDSUPPLIER
--/D)/--------------------------------------------------------------------
SELECT
CUSTOMER.NMCUSTOMER,
REQUEST.DTREQUEST,
REQUEST.VLTOTAL
FROM CUSTOMER 
LEFT JOIN REQUEST ON REQUEST.CDCUSTOMER = CUSTOMER.CDCUSTOMER
