--/A)/---------------------------------------------------------------------
SELECT 
PRODUCT.NMPRODUCT,
PRODUCT.VLPRICE,
SUPPLIER.NMSUPPLIER,
(PRODUCT.VLPRICE - (PRODUCT.VLPRICE * 0.1)) AS DISC_10,
(PRODUCT.VLPRICE - (PRODUCT.VLPRICE * 0.2)) AS DISC_20,
(PRODUCT.VLPRICE - (PRODUCT.VLPRICE * 0.3)) AS DISC_30
FROM PRODUCT JOIN SUPPLIER ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER

    WHERE (VLPRICE - (VLPRICE * 0.1)) > 15

ORDER BY NMPRODUCT, VLPRICE
--/B)/---------------------------------------------------------------------
SELECT 
NMPRODUCT, 
SUPPLIER.NMSUPPLIER, 
VLPRICE, 
(VLPRICE * QTSTOCK) AS TOTALSTOCKPROD,
VLPRICE * (QTSTOCK * 2) AS DOUBLE_STOCK
FROM PRODUCT JOIN SUPPLIER 
ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER

WHERE (VLPRICE * QTSTOCK) > 12000

ORDER BY SUPPLIER.NMSUPPLIER,PRODUCT.NMPRODUCT
--/C)/---------------------------------------------------------------------
SELECT * FROM CUSTOMER 
WHERE IDFONE<>NULL AND NMCUSTOMER LIKE 'J%' 
ORDER BY NMCUSTOMER
--/D)/---------------------------------------------------------------------
SELECT PRODUCT.NMPRODUCT,PRODUCT.VLPRICE,SUPPLIER.NMSUPPLIER 
FROM PRODUCT JOIN SUPPLIER ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER
WHERE SUPPLIER.NMSUPPLIER LIKE '%ICA%'
ORDER BY SUPPLIER.NMSUPPLIER
--/E)/---------------------------------------------------------------------
SELECT 
SUPPLIER.NMSUPPLIER, 
SUPPLIER.IDFONE, 
NMPRODUCT,
VLPRICE, 
(VLPRICE * QTSTOCK) AS TOTALPRODSTOCK
FROM PRODUCT JOIN SUPPLIER ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER
WHERE NMPRODUCT LIKE 'S%' AND VLPRICE > 50
ORDER BY NMSUPPLIER, VLPRICE
--/F)/---------------------------------------------------------------------
SELECT 
CUSTOMER.NMCUSTOMER,
PRODUCT.NMPRODUCT,
REQUEST.DTREQUEST,
REQUEST.DTDELIVER,
QTAMOUNT,
VLUNITARY,
(QTAMOUNT * VLUNITARY) AS TOTALPRODREQ

FROM PRODUCTREQUEST 

JOIN REQUEST ON REQUEST.CDREQUEST = PRODUCTREQUEST.CDREQUEST

JOIN CUSTOMER ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER

JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT

WHERE QTAMOUNT < 600 AND DTREQUEST BETWEEN '2003-08-01' AND '2003-08-31' AND PRODUCT.NMPRODUCT LIKE 'M%'
--/G)/---------------------------------------------------------------------
SELECT 
CUSTOMER.NMCUSTOMER, 
PRODUCT.NMPRODUCT, 
SUPPLIER.NMSUPPLIER,
SUPPLIER.IDFONE,
REQUEST.DTREQUEST, 
REQUEST.DTDELIVER, 
PRODUCTREQUEST.VLUNITARY
FROM PRODUCTREQUEST
JOIN REQUEST ON REQUEST.CDREQUEST = PRODUCTREQUEST.CDREQUEST
JOIN CUSTOMER ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER
JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT
JOIN SUPPLIER ON SUPPLIER.CDSUPPLIER = PRODUCT.CDSUPPLIER
WHERE VLPRICE > 20 AND SUPPLIER.IDFONE LIKE '%11%'

