--/A)/---------------------------------------------------------------------
SELECT 
PRODUCT.NMPRODUCT,
PRODUCT.VLPRICE,
SUPPLIER.NMSUPPLIER,
(PRODUCT.VLPRICE - (PRODUCT.VLPRICE * 0.1)) AS DISC_10,
(PRODUCT.VLPRICE - (PRODUCT.VLPRICE * 0.2)) AS DISC_20,
(PRODUCT.VLPRICE - (PRODUCT.VLPRICE * 0.3)) AS DISC_30
FROM PRODUCT JOIN SUPPLIER ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER

    WHERE (VLPRICE - (VLPRICE * 0.1)) > 15

ORDER BY NMPRODUCT, VLPRICE
--/B)/---------------------------------------------------------------------
SELECT 
NMPRODUCT, 
SUPPLIER.NMSUPPLIER, 
VLPRICE, 
(VLPRICE * QTSTOCK) AS TOTALSTOCKPROD,
VLPRICE * (QTSTOCK * 2) AS DOUBLE_STOCK
FROM PRODUCT JOIN SUPPLIER 
ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER

WHERE (VLPRICE * QTSTOCK) > 12000

ORDER BY SUPPLIER.NMSUPPLIER,PRODUCT.NMPRODUCT
