--/A)/------------------------------------------------------------------
SELECT DISTINCT NMPRODUCT FROM PRODUCT
SELECT NMPRODUCT FROM PRODUCT GROUP BY NMPRODUCT
--/B)/------------------------------------------------------------------
SELECT 
PRODUCT.NMPRODUCT, 
PRODUCTREQUEST.CDPRODUCT,
QTAMOUNT * COUNT(PRODUCT.NMPRODUCT) AS TOTALPED,
COUNT(PRODUCTREQUEST.CDPRODUCT) AS QTDPED 
FROM PRODUCTREQUEST JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT
GROUP BY PRODUCT.NMPRODUCT, PRODUCTREQUEST.CDPRODUCT, PRODUCTREQUEST.QTAMOUNT
--/C)/------------------------------------------------------------------
SELECT 
SUPPLIER.NMSUPPLIER,
SUM(PRODUCT.QTSTOCK) AS TOTALSUPP,
AVG(PRODUCT.VLPRICE) AS MEDIA,
COUNT(PRODUCT.CDPRODUCT) AS PRODQTD
FROM SUPPLIER JOIN PRODUCT ON SUPPLIER.CDSUPPLIER = PRODUCT.CDSUPPLIER
GROUP BY SUPPLIER.NMSUPPLIER
--/D)/------------------------------------------------------------------
SELECT 
CUSTOMER.NMCUSTOMER,
CUSTOMER.IDFONE,
MAX(REQUEST.VLTOTAL) AS MAXPRICE,
MIN(REQUEST.VLTOTAL) AS MINPRICE
FROM PRODUCTREQUEST 
JOIN REQUEST ON REQUEST.CDREQUEST = PRODUCTREQUEST.CDREQUEST
JOIN CUSTOMER ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER
GROUP BY CUSTOMER.NMCUSTOMER, CUSTOMER.IDFONE
--/E)/------------------------------------------------------------------
SELECT 
REQUEST.DTREQUEST,
CUSTOMER.NMCUSTOMER,
COUNT(DISTINCT PRODUCT.NMPRODUCT) AS DISTINCTPROD,
(PRODUCTREQUEST.QTAMOUNT * PRODUCTREQUEST.VLUNITARY) AS TOTALREQUEST,
(PRODUCTREQUEST.VLUNITARY/PRODUCTREQUEST.QTAMOUNT) AS MEDIA
FROM PRODUCTREQUEST
JOIN REQUEST ON REQUEST.CDREQUEST = PRODUCTREQUEST.CDREQUEST
JOIN CUSTOMER ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER
JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT
GROUP BY 
CUSTOMER.NMCUSTOMER, 
REQUEST.DTREQUEST, 
PRODUCTREQUEST.VLUNITARY, 
PRODUCTREQUEST.QTAMOUNT
ORDER BY COUNT(DISTINCT PRODUCT.NMPRODUCT)
--/F)/------------------------------------------------------------------
SELECT
SUPPLIER.NMSUPPLIER,
COUNT(CDPRODUCT) AS QTPRODSUPPLY
FROM PRODUCT JOIN SUPPLIER ON SUPPLIER.CDSUPPLIER = PRODUCT.CDSUPPLIER
GROUP BY SUPPLIER.NMSUPPLIER
HAVING COUNT(CDPRODUCT) > 1
--/G)/------------------------------------------------------------------
SELECT 
PRODUCT.NMPRODUCT,
COUNT(PRODUCT.CDPRODUCT) AS QTREQUESTED
FROM PRODUCT 
GROUP BY PRODUCT.NMPRODUCT
HAVING COUNT(PRODUCT.CDPRODUCT) < 2
--/H)/------------------------------------------------------------------
SELECT
CUSTOMER.NMCUSTOMER,
PRODUCT.NMPRODUCT,
SUPPLIER.NMSUPPLIER,
PRODUCTREQUEST.VLUNITARY * PRODUCTREQUEST.QTAMOUNT AS VLSPENT,
COUNT(REQUEST.CDCUSTOMER) AS QTREQCUST
FROM PRODUCTREQUEST
JOIN REQUEST ON REQUEST.CDREQUEST = PRODUCTREQUEST.CDREQUEST
JOIN CUSTOMER ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER
JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT
JOIN SUPPLIER ON SUPPLIER.CDSUPPLIER = PRODUCT.CDSUPPLIER
GROUP BY 
CUSTOMER.NMCUSTOMER,
PRODUCT.NMPRODUCT,
SUPPLIER.NMSUPPLIER, 
PRODUCTREQUEST.VLUNITARY, 
PRODUCTREQUEST.QTAMOUNT
HAVING COUNT(PRODUCTREQUEST.VLUNITARY * PRODUCTREQUEST.QTAMOUNT) > 1000
ORDER BY CUSTOMER.NMCUSTOMER,PRODUCT.NMPRODUCT
