----/A)/--------------------------------------------------
DELETE FROM REQUEST 
WHERE VLTOTAL < 1000 AND 
CDREQUEST NOT IN (SELECT CDREQUEST FROM PRODUCTREQUEST) AND 
MONTH(DTREQUEST) = 6 AND YEAR(DTREQUEST) = 2003
----/B)/---------------------------------------------------
UPDATE PRODUCT
SET PRODUCT.VLPRICE = (SELECT AVG(VLUNITARY) FROM PRODUCTREQUEST)
FROM PRODUCT 
JOIN PRODUCTREQUEST ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT
WHERE PRODUCT.CDPRODUCT IN (SELECT CDPRODUCT FROM PRODUCTREQUEST 
GROUP BY CDPRODUCT
HAVING SUM(PRODUCTREQUEST.QTAMOUNT) < 800)
----/C)/---------------------------------------------------
INSERT INTO CUSTOMER (CDCUSTOMER,NMCUSTOMER,NMADRESS,IDFONE)
SELECT (SELECT MAX(CDCUSTOMER)FROM CUSTOMER) + CDSUPPLIER AS NEWCDCUSTOMER, CDSUPPLIER, NMSUPPLIER, IDFONE 
FROM SUPPLIER
----/D)/---------------------------------------------------
UPDATE REQUEST
SET DTDELIVER = DTREQUEST + 30
WHERE ((DTREQUEST + 30) - (DTDELIVER)) < 10 AND REQUEST.VLTOTAL < 10000
