--/A)/---------------------------------------------------------------------
SELECT NMPRODUCT,
COUNT(PRODUCT.CDPRODUCT) AS QTPROD
FROM PRODUCT LEFT JOIN PRODUCTREQUEST ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT
GROUP BY NMPRODUCT
--/B)/---------------------------------------------------------------------
SELECT
SUPPLIER.NMSUPPLIER,
COUNT(SUPPLIER.CDSUPPLIER) AS NMPROD
FROM SUPPLIER LEFT JOIN PRODUCT ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER
GROUP BY NMSUPPLIER
--/C)/---------------------------------------------------------------------
SELECT 
SUPPLIER.NMSUPPLIER,
PRODUCT.NMPRODUCT,
SUM(PRODUCTREQUEST.CDPRODUCT) AS TOTALPROD
FROM PRODUCTREQUEST 
JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT
JOIN SUPPLIER ON SUPPLIER.CDSUPPLIER = PRODUCT.CDSUPPLIER
GROUP BY ROLLUP (SUPPLIER.NMSUPPLIER, PRODUCT.NMPRODUCT)
--/D)/---------------------------------------------------------------------
SELECT
CUSTOMER.NMCUSTOMER,
PRODUCT.NMPRODUCT,
SUM(VLUNITARY) AS TESTE
FROM PRODUCTREQUEST
JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT
JOIN REQUEST ON REQUEST.CDREQUEST= PRODUCTREQUEST.CDPRODUCT
JOIN SUPPLIER ON SUPPLIER.CDSUPPLIER = PRODUCT.CDSUPPLIER
JOIN CUSTOMER ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER
GROUP BY ROLLUP(CUSTOMER.NMCUSTOMER, PRODUCT.NMPRODUCT)
--/E)/---------------------------------------------------------------------
SELECT CUSTOMER.NMCUSTOMER, CUSTOMER.IDFONE
FROM CUSTOMER
LEFT JOIN REQUEST ON REQUEST.CDREQUEST = CUSTOMER.CDCUSTOMER
LEFT JOIN PRODUCTREQUEST ON PRODUCTREQUEST.CDREQUEST = REQUEST.CDREQUEST
GROUP BY CUSTOMER.NMCUSTOMER, CUSTOMER.IDFONE, PRODUCTREQUEST.QTAMOUNT
HAVING PRODUCTREQUEST.QTAMOUNT IS NULL
--/F)/---------------------------------------------------------------------
SELECT 
SUPPLIER.NMSUPPLIER,
SUPPLIER.IDFONE,
PRODUCT.NMPRODUCT
FROM SUPPLIER 
JOIN PRODUCT ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER
WHERE PRODUCT.NMPRODUCT LIKE '%leite em po%' OR PRODUCT.NMPRODUCT LIKE '%agua mineral%'
--/G)/---------------------------------------------------------------------
SELECT
PRODUCT.NMPRODUCT,
SUPPLIER.NMSUPPLIER
FROM PRODUCT
JOIN SUPPLIER ON SUPPLIER.CDSUPPLIER = PRODUCT.CDSUPPLIER
JOIN PRODUCTREQUEST ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT
GROUP BY PRODUCT.NMPRODUCT,
SUPPLIER.NMSUPPLIER
HAVING COUNT(PRODUCT.CDPRODUCT) > 3
